import type { Metadata } from 'next'
import { Lora, IM_Fell_Great_Primer_SC } from 'next/font/google'
import localFont from 'next/font/local'
import { Header, Footer } from '@/components/layout'
import './globals.css'

const brandon = localFont({
  src: [
    { path: '../public/fonts/brandon/HvDTrial_Brandon_Text_Regular.otf', weight: '400' },
    {
      path: '../public/fonts/brandon/HvDTrial_Brandon_Text_Regular_Italic.otf',
      style: 'italic',
      weight: '400',
    },
    { path: '../public/fonts/brandon/HvDTrial_Brandon_Text_Medium.otf', weight: '500' },
  ],
  variable: '--font-brandon',
  display: 'swap',
})

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-lora',
  display: 'swap',
})

const imFell = IM_Fell_Great_Primer_SC({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-fell',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${brandon.variable} ${lora.variable} ${imFell.variable} antialiased`}>
        <Header />
        <main className="container min-h-screen pt-41 lg:pt-20">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
